name: dist-pytorch
channels:
 - pytorch
 - nvidia
 - conda-forge
dependencies:
 - python=3.9
 - gcc=10
 - gxx=10
 - cudatoolkit=11.6
 - nccl=2.14
 - pytorch=1.13.0=py3.9_cuda11.6_cudnn8.3.2_0
 - torchvision
 - jupyterlab 
 - notebook 
 - ipykernel 
 - nb_conda_kernels 
 - nodejs
 - tensorboard
 - tensorboardx
 - pip
 - pip: 
     - ipython
     - ipywidgets
     - ipyparallel
     - matplotlib
     - bokeh==2.4.3
     - jupyterlab_nvdashboard
     - nvidia-pyindex
     - nvidia-dlprof
     - pytorch-lightning==1.9.0

     
