name: deepspeed-finetune
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - mpi4py
  - pip:
      - torch==2.5.1 --index-url https://download.pytorch.org/whl/cu121
      - torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu121
      - torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
      - transformers==4.51.2
      - deepspeed==0.16.5
      - accelerate==1.6.0
      - datasets==3.4.1
      - psrecord
      - pandas